spring:
  data:
    mongodb:
      host: localhost
      database: StudentDB
      port: 27017
  jpa:
    show-sql: true
    open-in-view: true

server:
  port: 8081

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true